>>> 'Pkg.add("Digits")' log
INFO: Cloning cache of Digits from git://github.com/greenflash1357/Digits.jl.git
INFO: Installing Digits v0.0.2
INFO: Package database updated

>>> 'Pkg.test("Digits")' log
Julia Version 0.4.0-dev+6477
Commit dce9d18* (2015-08-02 23:54 UTC)
Platform Info:
  System: Linux (x86_64-unknown-linux-gnu)
  CPU: Intel(R) Core(TM) i7-4960HQ CPU @ 2.60GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Nehalem)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
INFO: Testing Digits
WARNING: both Digits and Base export "contains"; uses of it in module Main must be qualified
ERROR: LoadError: test error in expression: contains(n,3456) == true
UndefVarError: contains not defined
 in anonymous at test.jl:90
 in do_test at test.jl:50
 in include at ./boot.jl:254
 in include_from_node1 at ./loading.jl:196
 in process_options at ./client.jl:308
 in _start at ./client.jl:411
 in anonymous at test.jl:90
 in do_test at test.jl:50
 in include at ./boot.jl:254
 in include_from_node1 at ./loading.jl:196
 in process_options at ./client.jl:308
 in _start at ./client.jl:411
while loading /home/vagrant/.julia/v0.4/Digits/test/runtests.jl, in expression starting on line 36
===============================[ ERROR: Digits ]================================

failed process: Process(`/home/vagrant/julia/bin/julia --check-bounds=yes --code-coverage=none --color=no /home/vagrant/.julia/v0.4/Digits/test/runtests.jl`, ProcessExited(1)) [1]

================================================================================
ERROR: Digits had test errors
 in error at ./error.jl:21
 in test at pkg/entry.jl:746
 in anonymous at pkg/dir.jl:31
 in cd at file.jl:22
 in cd at pkg/dir.jl:31
 in test at pkg.jl:71
 in process_options at ./client.jl:284
 in _start at ./client.jl:411

>>> End of log
