>>> 'Pkg.add("ExcelReaders")' log
INFO: Cloning cache of ExcelReaders from git://github.com/davidanthoff/ExcelReaders.jl.git
INFO: Installing ArrayViews v0.6.4
INFO: Installing Conda v0.2.0
INFO: Installing DataArrays v0.3.3
INFO: Installing DataFrames v0.7.3
INFO: Installing Dates v0.4.4
INFO: Installing Docile v0.5.23
INFO: Installing ExcelReaders v0.5.0
INFO: Installing GZip v0.2.19
INFO: Installing MacroTools v0.3.0
INFO: Installing PyCall v1.6.2
INFO: Installing Reexport v0.0.3
INFO: Installing SortingAlgorithms v0.0.6
INFO: Installing StatsBase v0.8.2
INFO: Installing StatsFuns v0.2.2
INFO: Building PyCall
INFO: No system-wide Python was found; got the following error:
could not spawn `'' -c "import distutils.sysconfig; print(distutils.sysconfig.get_config_var('VERSION'))"`: no such file or directory (ENOENT)
using the Python distribution in the Conda package
Fetching package metadata ...Error: Could not find anaconda.org user foo
===============================[ ERROR: PyCall ]================================

LoadError: failed process: Process(setenv(`/home/vagrant/.julia/v0.4/Conda/deps/usr/bin/conda install -y numpy`,Union{ASCIIString,UTF8String}["PYTHON=","PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/vagrant/julia/bin/","PWD=/vagrant/0.4AL","SHELL=/bin/bash","SSH_CONNECTION=10.0.2.2 52352 10.0.2.15 22","CONDARC=/home/vagrant/.julia/v0.4/Conda/deps/usr/condarc-julia","MAIL=/var/mail/vagrant","LANG=en_US.UTF-8","SHLVL=3","LOGNAME=vagrant","XDG_RUNTIME_DIR=/run/user/1000","XDG_SESSION_ID=3","OLDPWD=/home/vagrant","SSH_CLIENT=10.0.2.2 52352 22","_=/usr/bin/timeout","USER=vagrant","TERM=vt100","HOME=/home/vagrant","OPENBLAS_MAIN_FREE=1","JAVA_HOME=/usr/lib/jvm/java-7-oracle","PYTHONIOENCODING=UTF-8"]), ProcessExited(1)) [1]
while loading /home/vagrant/.julia/v0.4/PyCall/deps/build.jl, in expression starting on line 17

================================================================================

================================[ BUILD ERRORS ]================================

WARNING: PyCall had build errors.

 - packages with build errors remain installed in /home/vagrant/.julia/v0.4
 - build the package(s) and all dependencies with `Pkg.build("PyCall")`
 - build a single package by running its `deps/build.jl` script

================================================================================
INFO: Package database updated

>>> 'Pkg.test("ExcelReaders")' log
Julia Version 0.4.5
Commit 2ac304d (2016-03-18 00:58 UTC)
Platform Info:
  System: Linux (x86_64-unknown-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E3-1241 v3 @ 3.50GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Nehalem)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
INFO: Testing ExcelReaders
ERROR: LoadError: PyCall not properly installed. Please run Pkg.build("PyCall")
 in error at ./error.jl:21
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:320
 [inlined code] from none:2
 in anonymous at no file:0
 in process_options at ./client.jl:257
 in _start at ./client.jl:378
while loading /home/vagrant/.julia/v0.4/PyCall/src/PyCall.jl, in expression starting on line 36
ERROR: LoadError: Failed to precompile PyCall to /home/vagrant/.julia/lib/v0.4/PyCall.ji
 in error at ./error.jl:21
 in compilecache at loading.jl:400
 in require at ./loading.jl:240
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:320
 [inlined code] from none:2
 in anonymous at no file:0
 in process_options at ./client.jl:257
 in _start at ./client.jl:378
while loading /home/vagrant/.julia/v0.4/ExcelReaders/src/ExcelReaders.jl, in expression starting on line 5
ERROR: LoadError: Failed to precompile ExcelReaders to /home/vagrant/.julia/lib/v0.4/ExcelReaders.ji
 in error at ./error.jl:21
 in compilecache at loading.jl:400
 in require at ./loading.jl:266
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:320
 in process_options at ./client.jl:280
 in _start at ./client.jl:378
while loading /home/vagrant/.julia/v0.4/ExcelReaders/test/runtests.jl, in expression starting on line 1
============================[ ERROR: ExcelReaders ]=============================

failed process: Process(`/home/vagrant/julia/bin/julia --check-bounds=yes --code-coverage=none --color=no /home/vagrant/.julia/v0.4/ExcelReaders/test/runtests.jl`, ProcessExited(1)) [1]

================================================================================
ERROR: ExcelReaders had test errors
 in error at ./error.jl:21
 in test at pkg/entry.jl:803
 in anonymous at pkg/dir.jl:31
 in cd at file.jl:22
 in cd at pkg/dir.jl:31
 in test at pkg.jl:71
 in process_options at ./client.jl:257
 in _start at ./client.jl:378

>>> End of log
