>>> 'Pkg.add("FunctionalDataUtils")' log
INFO: Installing ArrayViews v0.6.4
INFO: Installing FactCheck v0.4.2
INFO: Installing FunctionalData v0.1.0
INFO: Installing FunctionalDataUtils v0.1.0
INFO: Installing MultivariateStats v0.2.1
INFO: Installing Reexport v0.0.3
INFO: Installing StatsBase v0.7.4
INFO: Installing StatsFuns v0.2.0
INFO: Package database updated
INFO: METADATA is out-of-date — you may not have the latest version of FunctionalDataUtils
INFO: Use `Pkg.update()` to get the latest versions of your packages

>>> 'Pkg.test("FunctionalDataUtils")' log
Julia Version 0.5.0-dev+1968
Commit e55c22a (2016-01-02 23:28 UTC)
Platform Info:
  System: Linux (x86_64-unknown-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E3-1241 v3 @ 3.50GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Nehalem)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
INFO: Testing FunctionalDataUtils
Starting runtests.jl  ...
machinelearning: randbase: 

computing: fasthash: ..................

computervision: iimg: .....
interp3: ......
interp3with01coords: ......
resize: ......
bwlabel: ...
border: 
signal (11): Segmentation fault
while loading ٿ�ٿ�ٿ�ٿ�ٿ�ٿ�ٿ�ٿ�ٿ�ٿ�ٿ�ٿ�ٿ�ٿ�ٿ�ٿ�ٿ�ٿ�ٿ�ٿ�ٿ�ٿ�ٿ�ٿ�ٿ�ٿ�ٿ�ٿ�ٿ�ٿ�ٿ�ٿ�ٿ�ٿ�ٿ�ٿ�ٿ�ٿ�ٿ�ٿ�ٿ�ٿ�ٿ�ٿ�ٿ�ٿ�ٿ�ٿ�ٿ�ٿ�ٿ�ٿ�ٿ�ٿ�ٿ�ٿ�ٿ�ٿ�ٿ�ٿ�ٿ�ٿ�ٿ�ٿ�ٿ�ٿ�ٿ�ٿ�ٿ�ٿ�ٿ�ٿ�ٿ�ٿ�ٿ�ٿ�ٿ�ٿ�ٿ�ٿ�ٿ�ٿ�ٿ�ٿ�ٿ�ٿ�ٿ�ٿ�ٿ�ٿ�ٿ�ٿ�ٿ�ٿ�ٿ�ٿ�ٿ�ٿ�ٿ�ٿ�ٿ�ٿ�ٿ�ٿ�ٿ�ٿ�ٿ�ٿ�ٿ�ٿ�ٿ�ٿ�ٿ�ٿ�ٿ�ٿ�ٿ�ٿ�ٿ�ٿ�ٿ�ٿ�ٿ�כinline] at cartesian.jl:62
_unsafe_batchsetindex! at multidimensional.jl:308
[inline] at multidimensional.jl:274
setindex! at abstractarray.jl:584
jl_apply_generic at /home/vagrant/julia/bin/../lib/julia/libjulia.so (unknown line)
map at /home/vagrant/.julia/v0.5/FunctionalData/src/computing.jl:126
jl_apply_generic at /home/vagrant/julia/bin/../lib/julia/libjulia.so (unknown line)
[inline] at array.jl:148
border at /home/vagrant/.julia/v0.5/FunctionalDataUtils/src/computervision.jl:518
jl_apply_generic at /home/vagrant/julia/bin/../lib/julia/libjulia.so (unknown line)
border at /home/vagrant/.julia/v0.5/FunctionalDataUtils/src/computervision.jl:516
jl_apply_generic at /home/vagrant/julia/bin/../lib/julia/libjulia.so (unknown line)
anonymous at /home/vagrant/.julia/v0.5/FactCheck/src/FactCheck.jl:271
do_fact at /home/vagrant/.julia/v0.5/FactCheck/src/FactCheck.jl:333
jl_apply_generic at /home/vagrant/julia/bin/../lib/julia/libjulia.so (unknown line)
[inline] at /home/vagrant/.julia/v0.5/FactCheck/src/FactCheck.jl:271
anonymous at /home/vagrant/.julia/v0.5/FunctionalDataUtils/test/runtests.jl:99
facts at /home/vagrant/.julia/v0.5/FactCheck/src/FactCheck.jl:448
shouldtestcontext at /home/vagrant/.julia/v0.5/FunctionalDataUtils/test/runtests.jl:6
jl_apply_generic at /home/vagrant/julia/bin/../lib/julia/libjulia.so (unknown line)
anonymous at /home/vagrant/.julia/v0.5/FunctionalDataUtils/test/runtests.jl:96
facts at /home/vagrant/.julia/v0.5/FactCheck/src/FactCheck.jl:448
shouldtest at /home/vagrant/.julia/v0.5/FunctionalDataUtils/test/runtests.jl:5
jl_apply_generic at /home/vagrant/julia/bin/../lib/julia/libjulia.so (unknown line)
unknown function (ip: 0x7fc1204dfa33)
unknown function (ip: 0x7fc1204dede6)
unknown function (ip: 0x7fc1204f41bc)
unknown function (ip: 0x7fc1204f4e7c)
jl_load at /home/vagrant/julia/bin/../lib/julia/libjulia.so (unknown line)
include at ./boot.jl:262
jl_apply_generic at /home/vagrant/julia/bin/../lib/julia/libjulia.so (unknown line)
include_from_node1 at ./loading.jl:401
jl_apply_generic at /home/vagrant/julia/bin/../lib/julia/libjulia.so (unknown line)
process_options at ./client.jl:249
_start at ./client.jl:301
unknown function (ip: 0x7fc11cd9b389)
jl_apply_generic at /home/vagrant/julia/bin/../lib/julia/libjulia.so (unknown line)
unknown function (ip: 0x401c27)
unknown function (ip: 0x4017ef)
__libc_start_main at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
unknown function (ip: 0x401835)
=========================[ ERROR: FunctionalDataUtils ]=========================

failed process: Process(`/home/vagrant/julia/bin/julia --check-bounds=yes --code-coverage=none --color=no /home/vagrant/.julia/v0.5/FunctionalDataUtils/test/runtests.jl`, ProcessSignaled(11)) [0]

================================================================================
ERROR: Base.Pkg.PkgError("FunctionalDataUtils had test errors")
 in test at pkg/entry.jl:671
 in anonymous at pkg/dir.jl:31
 in cd at file.jl:47
 in cd at pkg/dir.jl:31
 in test at pkg.jl:228
 in eval at ./boot.jl:265
 [inlined code] from ./sysimg.jl:14
 in process_options at ./client.jl:222
 in _start at ./client.jl:301

>>> End of log
