>>> 'Pkg.add("JuLIP")' log
INFO: Cloning cache of JuLIP from https://github.com/libAtoms/JuLIP.jl.git
INFO: Cloning cache of PyAMG from https://github.com/cortner/PyAMG.jl.git
INFO: Installing BinDeps v0.4.5
INFO: Installing Calculus v0.1.15
INFO: Installing Conda v0.4.0
INFO: Installing DiffBase v0.0.2
INFO: Installing ForwardDiff v0.3.3
INFO: Installing FunctionWrappers v0.0.1
INFO: Installing JuLIP v0.0.1
INFO: Installing LineSearches v0.1.3
INFO: Installing MacroTools v0.3.4
INFO: Installing NaNMath v0.2.2
INFO: Installing Optim v0.7.3
INFO: Installing PositiveFactorizations v0.0.3
INFO: Installing PyAMG v0.0.9
INFO: Installing PyCall v1.7.2
INFO: Installing Reexport v0.0.3
INFO: Installing SHA v0.3.0
INFO: Installing StaticArrays v0.1.3
INFO: Installing URIParser v0.1.6
INFO: Building Conda
INFO: Building PyCall
INFO: No system-wide Python was found; got the following error:
could not spawn `'' -c "import distutils.sysconfig; print(distutils.sysconfig.get_config_var('VERSION'))"`: no such file or directory (ENOENT)
using the Python distribution in the Conda package
Fetching package metadata .........
Solving package specifications: ..........

# All requested packages already installed.
# packages in environment at /home/vagrant/.julia/v0.6/Conda/deps/usr:
#
numpy                     1.11.2                   py27_0  
INFO: PyCall is using /home/vagrant/.julia/v0.6/Conda/deps/usr/bin/python (Python 2.7.13) at /home/vagrant/.julia/v0.6/Conda/deps/usr/bin/python, libpython = /home/vagrant/.julia/v0.6/Conda/deps/usr/lib/libpython2.7
INFO: Package database updated

>>> 'Pkg.test("JuLIP")' log
Julia Version 0.6.0-dev.1973
Commit f4ed16b (2017-01-06 23:58 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E3-1241 v3 @ 3.50GHz
  WORD_SIZE: 64
           Ubuntu 14.04.5 LTS
  uname: Linux 3.13.0-106-generic #153-Ubuntu SMP Tue Dec 6 15:44:32 UTC 2016 x86_64 x86_64
Memory: 2.9392738342285156 GB (1578.734375 MB free)
Uptime: 35837.0 sec
Load Avg:  0.87939453125  0.94580078125  1.01318359375
Intel(R) Xeon(R) CPU E3-1241 v3 @ 3.50GHz: 
       speed         user         nice          sys         idle          irq
#1  3499 MHz    1984109 s       5516 s     200562 s     983459 s        112 s
#2  3499 MHz     685739 s       1052 s     134118 s    2643507 s          1 s

  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Nehalem)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, haswell)
Environment:
  TERM = vt100
  LD_LIBRARY_PATH = :/usr/local/lib/
  PATH = /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/vagrant/julia/bin/
  JAVA_HOME = /usr/lib/jvm/java-7-oracle
  HOME = /home/vagrant

Package Directory: /home/vagrant/.julia/v0.6
2 required packages:
 - JSON                          0.8.0
 - JuLIP                         0.0.1
22 additional packages:
 - BinDeps                       0.4.5
 - Calculus                      0.1.15
 - Compat                        0.10.0
 - CompilerTools                 0.2.1
 - Conda                         0.4.0
 - DataStructures                0.5.0
 - DiffBase                      0.0.2
 - DocOpt                        0.2.0
 - ForwardDiff                   0.3.3
 - FunctionWrappers              0.0.1
 - LineSearches                  0.1.3
 - MacroTools                    0.3.4
 - NaNMath                       0.2.2
 - Optim                         0.7.3
 - ParallelAccelerator           0.2.2              6da2e374 (dirty)
 - PositiveFactorizations        0.0.3
 - PyAMG                         0.0.9
 - PyCall                        1.7.2
 - Reexport                      0.0.3
 - SHA                           0.3.0
 - StaticArrays                  0.1.3
 - URIParser                     0.1.6
INFO: Testing JuLIP
ERROR: LoadError: LoadError: LoadError: InitError: UndefVarError: name not defined
Stacktrace:
 [1] macro expansion at /home/vagrant/.julia/v0.6/PyCall/src/exception.jl:78 [inlined]
 [2] pyimport(::String) at /home/vagrant/.julia/v0.6/PyCall/src/PyCall.jl:387
 [3] __init__() at /home/vagrant/.julia/v0.6/PyCall/src/pyinit.jl:58
 [4] _include_from_serialized(::String) at ./loading.jl:150
 [5] _require_from_serialized(::Int64, ::Symbol, ::String, ::Bool) at ./loading.jl:187
 [6] require(::Symbol) at ./loading.jl:425
 [7] include_from_node1(::String) at ./loading.jl:532
 [8] include(::String) at ./sysimg.jl:14
 [9] include_from_node1(::String) at ./loading.jl:532
during initialization of module PyCall
while loading /home/vagrant/.julia/v0.6/JuLIP/src/arrayconversions.jl, in expression starting on line 3
while loading /home/vagrant/.julia/v0.6/JuLIP/src/JuLIP.jl, in expression starting on line 13
while loading /home/vagrant/.julia/v0.6/JuLIP/test/runtests.jl, in expression starting on line 2
================================[ ERROR: JuLIP ]================================

failed process: Process(`/home/vagrant/julia/bin/julia -Cx86-64 -J/home/vagrant/julia/lib/julia/sys.so --compile=yes --depwarn=yes --check-bounds=yes --code-coverage=none --color=no --compilecache=yes /home/vagrant/.julia/v0.6/JuLIP/test/runtests.jl`, ProcessExited(1)) [1]

================================================================================
ERROR: JuLIP had test errors

>>> End of log
