>>> 'Pkg.add("NumericFuns")' log
INFO: Installing NumericFuns v0.2.4
INFO: Package database updated

>>> 'Pkg.test("NumericFuns")' log
Julia Version 0.5.0-pre+5637
Commit f578be3 (2016-07-22 22:32 UTC)
Platform Info:
  System: Linux (x86_64-unknown-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E3-1241 v3 @ 3.50GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Nehalem)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, haswell)
INFO: Testing NumericFuns
running mathfuns.jl ...
running functors.jl ...
    macros
    arithmetic operators
    comparison operators
    logical operators
    bitwise operators
    arithmetic functions
WARNING: both NumericFuns and Base export "RemFun"; uses of it in module Main must be qualified
WARNING: both NumericFuns and Base export "ModFun"; uses of it in module Main must be qualified
WARNING: both NumericFuns and Base export "MaxFun"; uses of it in module Main must be qualified
WARNING: both NumericFuns and Base export "MinFun"; uses of it in module Main must be qualified
ERROR: LoadError: LoadError: UndefVarError: RemFun not defined
 in anonymous at ./<missing>:?
 in include_from_node1(::String) at ./loading.jl:426
 in macro expansion; at /home/vagrant/.julia/v0.5/NumericFuns/test/runtests.jl:6 [inlined]
 in anonymous at ./<missing>:?
 in include_from_node1(::String) at ./loading.jl:426
 in process_options(::Base.JLOptions) at ./client.jl:262
 in _start() at ./client.jl:318
while loading /home/vagrant/.julia/v0.5/NumericFuns/test/functors.jl, in expression starting on line 71
while loading /home/vagrant/.julia/v0.5/NumericFuns/test/runtests.jl, in expression starting on line 3
=============================[ ERROR: NumericFuns ]=============================

failed process: Process(`/home/vagrant/julia/bin/julia -Cx86-64 -J/home/vagrant/julia/lib/julia/sys.so --compile=yes --depwarn=yes --check-bounds=yes --code-coverage=none --color=no --compilecache=yes /home/vagrant/.julia/v0.5/NumericFuns/test/runtests.jl`, ProcessExited(1)) [1]

================================================================================
ERROR: NumericFuns had test errors
 in #test#61(::Bool, ::Function, ::Array{AbstractString,1}) at ./pkg/entry.jl:736
 in (::Base.Pkg.Entry.#kw##test)(::Array{Any,1}, ::Base.Pkg.Entry.#test, ::Array{AbstractString,1}) at ./<missing>:0
 in (::Base.Pkg.Dir.##2#3{Array{Any,1},Base.Pkg.Entry.#test,Tuple{Array{AbstractString,1}}})() at ./pkg/dir.jl:31
 in cd(::Base.Pkg.Dir.##2#3{Array{Any,1},Base.Pkg.Entry.#test,Tuple{Array{AbstractString,1}}}, ::String) at ./file.jl:59
 in #cd#1(::Array{Any,1}, ::Function, ::Function, ::Array{AbstractString,1}, ::Vararg{Array{AbstractString,1},N}) at ./pkg/dir.jl:31
 in (::Base.Pkg.Dir.#kw##cd)(::Array{Any,1}, ::Base.Pkg.Dir.#cd, ::Function, ::Array{AbstractString,1}, ::Vararg{Array{AbstractString,1},N}) at ./<missing>:0
 in #test#3(::Bool, ::Function, ::String, ::Vararg{String,N}) at ./pkg/pkg.jl:258
 in test(::String, ::Vararg{String,N}) at ./pkg/pkg.jl:258
 in eval(::Module, ::Any) at ./boot.jl:234
 in process_options(::Base.JLOptions) at ./client.jl:239
 in _start() at ./client.jl:318

>>> End of log
