>>> 'Pkg.add("SGP4")' log
INFO: Cloning cache of SGP4 from git://github.com/crbinz/SGP4.jl.git
INFO: Installing BinDeps v0.3.21
INFO: Installing Conda v0.2.3
INFO: Installing Dates v0.3.2
INFO: Installing HttpCommon v0.1.2
INFO: Installing PyCall v1.2.0
INFO: Installing SGP4 v0.0.3
INFO: Installing SHA v0.2.1
INFO: Installing URIParser v0.0.7
INFO: Building PyCall
INFO: No system-wide Python was found; got the following error:
could not spawn `'' -c "import distutils.sysconfig; print(distutils.sysconfig.get_config_var('VERSION'))"`: no such file or directory (ENOENT)
using the Python distribution in the Conda package
Fetching package metadata .......
Solving package specifications: ..........

# All requested packages already installed.
# packages in environment at /home/vagrant/.julia/v0.3/Conda/deps/usr:
#
numpy                     1.11.1                   py27_0  
INFO: PyCall is using /home/vagrant/.julia/v0.3/Conda/deps/usr/bin/python (Python 2.7.12) at /home/vagrant/.julia/v0.3/Conda/deps/usr/bin/python, libpython = /home/vagrant/.julia/v0.3/Conda/deps/usr/lib/libpython2.7.so
INFO: Package database updated

>>> 'Pkg.test("SGP4")' log
Julia Version 0.3.12
Commit 80aa779 (2015-10-26 12:41 UTC)
Platform Info:
  System: Linux (x86_64-unknown-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E3-1241 v3 @ 3.50GHz
  WORD_SIZE: 64
           Ubuntu 14.04.5 LTS
  uname: Linux 3.13.0-93-generic #140-Ubuntu SMP Mon Jul 18 21:21:05 UTC 2016 x86_64 x86_64
Memory: 2.4471054077148438 GB (315.6015625 MB free)
Uptime: 16674.0 sec
Load Avg:  1.0859375  0.99853515625  0.96533203125
Intel(R) Xeon(R) CPU E3-1241 v3 @ 3.50GHz: 
       speed         user         nice          sys         idle          irq
#1  3500 MHz     675858 s       6518 s      82489 s     713477 s         30 s
#2  3500 MHz     478909 s         73 s      75700 s    1025064 s          1 s

  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Nehalem)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
Environment:
  TERM = vt100
  LD_LIBRARY_PATH = :/usr/local/lib/
  PATH = /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/vagrant/julia/bin/
  JAVA_HOME = /usr/lib/jvm/java-7-oracle
  HOME = /home/vagrant

Package Directory: /home/vagrant/.julia/v0.3
2 required packages:
 - JSON                          0.6.0
 - SGP4                          0.0.3
8 additional packages:
 - BinDeps                       0.3.21
 - Compat                        0.8.6
 - Conda                         0.2.3
 - Dates                         0.3.2
 - HttpCommon                    0.1.2
 - PyCall                        1.2.0
 - SHA                           0.2.1
 - URIParser                     0.0.7
INFO: Testing SGP4
ERROR: PyError (:PyImport_ImportModule) <type 'exceptions.ImportError'>
ImportError('No module named sgp4.io',)

 in pyerr_check at /home/vagrant/.julia/v0.3/PyCall/src/exception.jl:61
 in pyimport at /home/vagrant/.julia/v0.3/PyCall/src/PyCall.jl:81
 in include at ./boot.jl:245
 in include_from_node1 at ./loading.jl:128
 in reload_path at loading.jl:152
 in _require at loading.jl:67
 in require at loading.jl:51
 in include at ./boot.jl:245
 in include_from_node1 at loading.jl:128
 in process_options at ./client.jl:285
 in _start at ./client.jl:354
while loading /home/vagrant/.julia/v0.3/SGP4/src/SGP4.jl, in expression starting on line 341
while loading /home/vagrant/.julia/v0.3/SGP4/test/runtests.jl, in expression starting on line 1
================================[ ERROR: SGP4 ]=================================

failed process: Process(`/home/vagrant/julia/bin/julia /home/vagrant/.julia/v0.3/SGP4/test/runtests.jl`, ProcessExited(1)) [1]

================================================================================
INFO: No packages to install, update or remove
ERROR: SGP4 had test errors
 in error at error.jl:21
 in test at pkg/entry.jl:718
 in anonymous at pkg/dir.jl:28
 in cd at ./file.jl:20
 in cd at pkg/dir.jl:28
 in test at pkg.jl:67
 in process_options at ./client.jl:213
 in _start at ./client.jl:354

>>> End of log
