>>> 'Pkg.add("SGP4")' log
INFO: Cloning cache of SGP4 from git://github.com/crbinz/SGP4.jl.git
INFO: Installing BinDeps v0.4.5
INFO: Installing Conda v0.5.1
INFO: Installing Dates v0.4.4
INFO: Installing MacroTools v0.3.5
INFO: Installing PyCall v1.10.0
INFO: Installing SGP4 v0.2.0
INFO: Installing SHA v0.3.1
INFO: Installing URIParser v0.1.8
INFO: Building Conda
INFO: Building PyCall
INFO: Using the Python distribution in the Conda package by default.
To use a different Python version, set ENV["PYTHON"]="pythoncommand" and re-run Pkg.build("PyCall").
Fetching package metadata .........
Solving package specifications: .

# All requested packages already installed.
# packages in environment at /home/vagrant/.julia/v0.4/Conda/deps/usr:
#
numpy                     1.12.0                   py27_0  
INFO: PyCall is using /home/vagrant/.julia/v0.4/Conda/deps/usr/bin/python (Python 2.7.13) at /home/vagrant/.julia/v0.4/Conda/deps/usr/bin/python, libpython = /home/vagrant/.julia/v0.4/Conda/deps/usr/lib/libpython2.7
INFO: /home/vagrant/.julia/v0.4/PyCall/deps/deps.jl has not changed
INFO: /home/vagrant/.julia/v0.4/PyCall/deps/PYTHON has not changed
INFO: Package database updated
INFO: METADATA is out-of-date â€” you may not have the latest version of SGP4
INFO: Use `Pkg.update()` to get the latest versions of your packages

>>> 'Pkg.test("SGP4")' log
Julia Version 0.4.7
Commit ae26b25 (2016-09-18 16:17 UTC)
Platform Info:
  System: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E3-1241 v3 @ 3.50GHz
  WORD_SIZE: 64
           Ubuntu 14.04.5 LTS
  uname: Linux 3.13.0-108-generic #155-Ubuntu SMP Wed Jan 11 16:58:52 UTC 2017 x86_64 x86_64
Memory: 2.9392738342285156 GB (2270.82421875 MB free)
Uptime: 30057.0 sec
Load Avg:  1.091796875  1.001953125  0.9853515625
Intel(R) Xeon(R) CPU E3-1241 v3 @ 3.50GHz: 
       speed         user         nice          sys         idle          irq
#1  3500 MHz    1489915 s       2077 s     126069 s    1059543 s        183 s
#2  3500 MHz     942271 s       4115 s     113120 s    1795862 s          7 s

  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Nehalem)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
Environment:
  TERM = vt100
  LD_LIBRARY_PATH = :/usr/local/lib/
  PATH = /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/vagrant/julia/bin/
  JAVA_HOME = /usr/lib/jvm/java-7-oracle
  HOME = /home/vagrant

Package Directory: /home/vagrant/.julia/v0.4
2 required packages:
 - JSON                          0.8.3
 - SGP4                          0.2.0
8 additional packages:
 - BinDeps                       0.4.5
 - Compat                        0.18.0
 - Conda                         0.5.1
 - Dates                         0.4.4
 - MacroTools                    0.3.5
 - PyCall                        1.10.0
 - SHA                           0.3.1
 - URIParser                     0.1.8
INFO: Testing SGP4
INFO: Installing sgp4.io via the Conda sgp4 package...
Fetching package metadata ....
WARNING: The remote server could not find the noarch directory for the
requested channel with url: https://conda.anaconda.org/poliastro

It is possible you have given conda an invalid channel. Please double-check
your conda configuration using `conda config --show`.

If the requested url is in fact a valid conda channel, please request that the
channel administrator create `noarch/repodata.json` and associated
`noarch/repodata.json.bz2` files, even if `noarch/repodata.json` is empty.
$ mkdir noarch
$ echo '{}' > noarch/repodata.json
$ bzip2 -k noarch/repodata.json
.......


PackageNotFoundError: Package not found: '' Package missing in current linux-64 channels: 
  - sgp4

You can search for packages on anaconda.org with

    anaconda search -t conda sgp4

You may need to install the anaconda-client command line client with

    conda install anaconda-client


ERROR: LoadError: InitError: failed process: Process(setenv(`/home/vagrant/.julia/v0.4/Conda/deps/usr/bin/conda install -y sgp4`,Union{ASCIIString,UTF8String}["PYTHON=","PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/vagrant/julia/bin/","PWD=/vagrant/0.4MZ","SHELL=/bin/bash","SSH_CONNECTION=10.0.2.2 60476 10.0.2.15 22","LD_LIBRARY_PATH=:/usr/local/lib/","CONDARC=/home/vagrant/.julia/v0.4/Conda/deps/usr/condarc-julia.yml","MAIL=/var/mail/vagrant","LANG=en_US.UTF-8","SHLVL=4","LOGNAME=vagrant","XDG_RUNTIME_DIR=/run/user/1000","XDG_SESSION_ID=3","CONDA_PREFIX=/home/vagrant/.julia/v0.4/Conda/deps/usr","SSH_CLIENT=10.0.2.2 60476 22","_=/usr/bin/timeout","CONDA_DEFAULT_ENV=/home/vagrant/.julia/v0.4/Conda/deps/usr","USER=vagrant","TERM=vt100","HOME=/home/vagrant","OPENBLAS_MAIN_FREE=1","JAVA_HOME=/usr/lib/jvm/java-7-oracle"]), ProcessExited(1)) [1]
 in run at ./process.jl:531
 in pyimport_conda at /home/vagrant/.julia/v0.4/PyCall/src/PyCall.jl:483
 in __init__ at /home/vagrant/.julia/v0.4/SGP4/src/SGP4.jl:14
 in _include_from_serialized at loading.jl:62
 in _require_from_serialized at loading.jl:87
 in require at ./loading.jl:280
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:333
 in process_options at ./client.jl:280
 in _start at ./client.jl:378
during initialization of module SGP4
while loading /home/vagrant/.julia/v0.4/SGP4/test/runtests.jl, in expression starting on line 1
================================[ ERROR: SGP4 ]=================================

failed process: Process(`/home/vagrant/julia/bin/julia --check-bounds=yes --code-coverage=none --color=no /home/vagrant/.julia/v0.4/SGP4/test/runtests.jl`, ProcessExited(1)) [1]

================================================================================
ERROR: SGP4 had test errors
 in error at ./error.jl:21
 in test at pkg/entry.jl:803
 in anonymous at pkg/dir.jl:31
 in cd at file.jl:22
 in cd at pkg/dir.jl:31
 in test at pkg.jl:71
 in process_options at ./client.jl:257
 in _start at ./client.jl:378

>>> End of log
