>>> 'Pkg.add("SystemImageBuilder")' log
INFO: Cloning cache of SystemImageBuilder from git://github.com/rened/SystemImageBuilder.jl.git
INFO: Installing FunctionalData v0.0.15
INFO: Installing SystemImageBuilder v0.0.7
INFO: Package database updated
INFO: METADATA is out-of-date â€” you may not have the latest version of SystemImageBuilder
INFO: Use `Pkg.update()` to get the latest versions of your packages

>>> 'Pkg.test("SystemImageBuilder")' log
Julia Version 0.4.0-pre+7304
Commit b3a1be5 (2015-09-05 13:59 UTC)
Platform Info:
  System: Linux (x86_64-unknown-linux-gnu)
  CPU: Intel(R) Core(TM) i5-2500K CPU @ 3.30GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
INFO: Computing test dependencies for SystemImageBuilder...
INFO: Installing FactCheck v0.4.0
INFO: Testing SystemImageBuilder
INFO: System image already loaded at /home/vagrant/julia/lib/julia/sys.so, set force to override
ERROR: LoadError: LoadError: /home/vagrant/julia/bin/../lib/julia/julia/sys.ji does not seem to be the correct path of sys.ji
 in error at error.jl:21
 in include at ./boot.jl:260
 in include_from_node1 at ./loading.jl:271
 in require at ./loading.jl:210
 in include at ./boot.jl:260
 in include_from_node1 at ./loading.jl:271
 in process_options at ./client.jl:308
 in _start at ./client.jl:411
while loading /home/vagrant/.julia/v0.4/SystemImageBuilder/src/SystemImageBuilder.jl, in expression starting on line 43
while loading /home/vagrant/.julia/v0.4/SystemImageBuilder/test/runtests.jl, in expression starting on line 1
=========================[ ERROR: SystemImageBuilder ]==========================

failed process: Process(`/home/vagrant/julia/bin/julia --check-bounds=yes --code-coverage=none --color=no /home/vagrant/.julia/v0.4/SystemImageBuilder/test/runtests.jl`, ProcessExited(1)) [1]

================================================================================
INFO: Removing FactCheck v0.4.0
ERROR: SystemImageBuilder had test errors
 in error at ./error.jl:21
 [inlined code] from pkg/entry.jl:753
 in __test#412__ at no file:0
 in test at no file
 in anonymous at pkg/dir.jl:31
 in cd at file.jl:22
 [inlined code] from pkg/dir.jl:31
 in __cd#396__ at no file:0
 in cd at no file
 in __test#420__ at no file
 in test at no file
 in process_options at ./client.jl:284
 in _start at ./client.jl:411

>>> End of log
